import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { UserProvider } from "./context_selectedPlace"
import NavCard from "./NavCard";
// import logo from './logo.svg';
import { HomeIcon } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full flex bg-gradient-to-b from-white to-[#BADFDB]  antialiased`}
      >
        <UserProvider>

          <main className="flex-1 min-h-screen overflow-auto p-4">
            {/* <SidebarTrigger /> */}
            {children}
          </main>

        </UserProvider>
      </body>
    </html>
  );
}
