import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { UserProvider } from "./context_selectedPlace"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full flex bg-slate-50 antialiased`}
      >
        <UserProvider>
        <SidebarProvider>
          <AppSidebar />

          <main className="flex-1 min-h-screen overflow-auto p-4">
            {/* <SidebarTrigger /> */}
            {children}
          </main>
        </SidebarProvider>
        </UserProvider>
      </body>
    </html>
  );
}
